// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: WaterTank

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Main_Screen
void ui_Main_Screen_screen_init(void);
lv_obj_t * ui_Main_Screen;
lv_obj_t * ui_TopInfoBar1;
lv_obj_t * ui_Spinner2;
lv_obj_t * ui_imWifiConnected4;
lv_obj_t * ui_imWifiDisconnected4;
lv_obj_t * ui_imInternetOK4;
lv_obj_t * ui_imInternetNOK4;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_Main;
lv_obj_t * ui_Bar1;
lv_obj_t * ui_lblMaxValue;
lv_obj_t * ui_lblMinValue;
lv_obj_t * ui_lblMax;
lv_obj_t * ui_lblMin;
lv_obj_t * ui_lblCurrentLiter;
lv_obj_t * ui_THPanel;
lv_obj_t * ui_lblTempValue;
lv_obj_t * ui_lblHumValue;
lv_obj_t * ui_Chart2;
lv_obj_t * ui_Chart2_Xaxis;
lv_obj_t * ui_Chart2_Yaxis1;
lv_obj_t * ui_Chart2_Yaxis2;
lv_obj_t * ui_lblH;
lv_obj_t * ui_Statistic;
lv_obj_t * ui_Arc2;
lv_obj_t * ui_Param;
lv_obj_t * ui_Settings;
lv_obj_t * ui_About;
lv_obj_t * ui_ConBuildDate;
lv_obj_t * ui_lblBuildDate;
lv_obj_t * ui_lblBuildDateValue;
lv_obj_t * ui_ConBuildVersion;
lv_obj_t * ui_lblBuildVersion;
lv_obj_t * ui_lblBuildVersionValue;
lv_obj_t * ui_ConRunTime;
lv_obj_t * ui_lblRunTime;
lv_obj_t * ui_lblRunTimeValue;
lv_obj_t * ui_ConGitHub;
lv_obj_t * ui_lblGit;
lv_obj_t * ui_lblGitHub;
lv_obj_t * ui_ConAuth;
lv_obj_t * ui_lblGit1;
lv_obj_t * ui_lblGitHub1;


// SCREEN: ui_Wifi_Settings
void ui_Wifi_Settings_screen_init(void);
lv_obj_t * ui_Wifi_Settings;
lv_obj_t * ui_TopInfoBar2;
lv_obj_t * ui_Spinner4;
lv_obj_t * ui_imWifiConnected2;
lv_obj_t * ui_imWifiDisconnected2;
lv_obj_t * ui_imInternetOK2;
lv_obj_t * ui_imInternetNOK2;
lv_obj_t * ui_lblTime1;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Container9;
lv_obj_t * ui_Label4;
lv_obj_t * ui_lblWifiStatus;
lv_obj_t * ui_Container10;
lv_obj_t * ui_Label15;
lv_obj_t * ui_lblWifiSSID;
lv_obj_t * ui_Container11;
lv_obj_t * ui_Label17;
lv_obj_t * ui_lblWifiIP;
lv_obj_t * ui_Container12;
lv_obj_t * ui_Label20;
lv_obj_t * ui_lblWifiRSSI;
lv_obj_t * ui_Container13;
lv_obj_t * ui_Label22;
lv_obj_t * ui_lblWifiChannel;
lv_obj_t * ui_Container14;
lv_obj_t * ui_Label24;
lv_obj_t * ui_lblWifiSecurity;
lv_obj_t * ui_Container16;
lv_obj_t * ui_Label27;
lv_obj_t * ui_lblTime;
lv_obj_t * ui_lblTimeZone;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Container15;
lv_obj_t * ui_Label14;
void ui_event_btnForgetWifi(lv_event_t * e);
lv_obj_t * ui_btnForgetWifi;
lv_obj_t * ui_Label25;


// SCREEN: ui_WifiScanResult
void ui_WifiScanResult_screen_init(void);
lv_obj_t * ui_WifiScanResult;
lv_obj_t * ui_TopInfoBar;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_imWifiConnected1;
lv_obj_t * ui_imWifiDisconnected1;
lv_obj_t * ui_imInternetOK1;
lv_obj_t * ui_imInternetNOK1;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Label1;
void ui_event_funcWifiScan(lv_event_t * e);
lv_obj_t * ui_funcWifiScan;
lv_obj_t * ui_Label2;
void ui_event_btnback(lv_event_t * e);
lv_obj_t * ui_btnback;
lv_obj_t * ui_Label19;
lv_obj_t * ui_PanelWifiList;
lv_obj_t * ui_Label3;
lv_obj_t * ui_panelScanningWifi;
lv_obj_t * ui_Label26;


// SCREEN: ui_ConnectToWifi
void ui_ConnectToWifi_screen_init(void);
lv_obj_t * ui_ConnectToWifi;
lv_obj_t * ui_TopInfoBar3;
lv_obj_t * ui_Spinner3;
lv_obj_t * ui_imWifiConnected3;
lv_obj_t * ui_imWifiDisconnected3;
lv_obj_t * ui_imInternetOK3;
lv_obj_t * ui_imInternetNOK3;
void ui_event_Keyboard1(lv_event_t * e);
lv_obj_t * ui_Keyboard1;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Label8;
lv_obj_t * ui_lblWifiSSIDToBeConnect;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Label10;
lv_obj_t * ui_textareaWifiPassword;
lv_obj_t * ui_Container7;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label12;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label13;
lv_obj_t * ui_panelConnectionSuccess;
lv_obj_t * ui_Label16;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label18;
lv_obj_t * ui_panelNotConnected;
lv_obj_t * ui_Label21;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label23;
lv_obj_t * ui_panelConnectingToWifi;
lv_obj_t * ui_Label9;
lv_obj_t * ui_lblAttemptNumber;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiScanResult, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WifiScanResult_screen_init);
    }
}
void ui_event_btnForgetWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        funcResetWifi(e);
    }
}
void ui_event_funcWifiScan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        funcWifiScan(e);
    }
}
void ui_event_btnback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Wifi_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Wifi_Settings_screen_init);
    }
}
void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_textareaWifiPassword);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ConnectToWifiButtonPress(e);
    }
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiScanResult, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WifiScanResult_screen_init);
    }
}
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Wifi_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Wifi_Settings_screen_init);
        _ui_flag_modify(ui_panelConnectionSuccess, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_panelNotConnected, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_CLICKED) {
        RetryButtonWrongPassword(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Main_Screen_screen_init();
    ui_Wifi_Settings_screen_init();
    ui_WifiScanResult_screen_init();
    ui_ConnectToWifi_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Main_Screen);
}
