// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: WaterTank

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Main_Screen
void ui_Main_Screen_screen_init(void);
lv_obj_t * ui_Main_Screen;
lv_obj_t * ui_TopInfoBar1;
lv_obj_t * ui_Spinner2;
lv_obj_t * ui_imWifiInternetOK1;
lv_obj_t * ui_imWifiDisconnected1;
lv_obj_t * ui_imWifiConnectedNoInternet1;
lv_obj_t * ui_lblDataNTime;
lv_obj_t * ui_lblWifiRSSI2;
lv_obj_t * ui_MainTabView;
lv_obj_t * ui_Main;
lv_obj_t * ui_PanelBar;
lv_obj_t * ui_BarCurrentState;
lv_obj_t * ui_lblCurrentLiter1;
lv_obj_t * ui_lblMaxValue;
lv_obj_t * ui_lblMinValue;
lv_obj_t * ui_lblMax;
lv_obj_t * ui_lblMin;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_lblCurrentLiter;
lv_obj_t * ui_THPanel;
lv_obj_t * ui_lblTempValue;
lv_obj_t * ui_lblHumValue;
lv_obj_t * ui_Chart2;
lv_obj_t * ui_Chart2_Xaxis;
lv_obj_t * ui_Chart2_Yaxis1;
lv_obj_t * ui_Chart2_Yaxis2;
lv_obj_t * ui_lblL;
lv_obj_t * ui_ChartActualLiter;
lv_obj_t * ui_ChartActualLiter_Xaxis;
lv_obj_t * ui_ChartActualLiter_Yaxis1;
lv_obj_t * ui_ChartActualLiter_Yaxis2;
lv_obj_t * ui_lblH1;
lv_obj_t * ui_lblPer;
lv_obj_t * ui_Statistic;
lv_obj_t * ui_Container5;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_lblActualDistance;
lv_obj_t * ui_lblActualDistanceValue;
lv_obj_t * ui_lblMinDistance;
lv_obj_t * ui_lblMinDistanceValue;
lv_obj_t * ui_lblMaxDistance;
lv_obj_t * ui_lblMaxDistanceValue;
lv_obj_t * ui_lblDistance;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label31;
lv_obj_t * ui_Param;
lv_obj_t * ui_ContTankType;
lv_obj_t * ui_Label32;
void ui_event_DropdownParamTankType(lv_event_t * e);
lv_obj_t * ui_DropdownParamTankType;
lv_obj_t * ui_ContRectangle;
lv_obj_t * ui_lblWide;
lv_obj_t * ui_lblDepth;
lv_obj_t * ui_lblHeight;
lv_obj_t * ui_Label35;
void ui_event_TextAreaRectangleWide(lv_event_t * e);
lv_obj_t * ui_TextAreaRectangleWide;
void ui_event_TextAreaRectangleDepth(lv_event_t * e);
lv_obj_t * ui_TextAreaRectangleDepth;
void ui_event_TextAreaRectangleHeight(lv_event_t * e);
lv_obj_t * ui_TextAreaRectangleHeight;
lv_obj_t * ui_ContCilinder;
lv_obj_t * ui_lblDiameter;
lv_obj_t * ui_lblHeight1;
lv_obj_t * ui_Label33;
void ui_event_TextAreaCilinderDiameter(lv_event_t * e);
lv_obj_t * ui_TextAreaCilinderDiameter;
void ui_event_TextAreaCilinderHeight(lv_event_t * e);
lv_obj_t * ui_TextAreaCilinderHeight;
lv_obj_t * ui_ContMinMax;
lv_obj_t * ui_lblDiameter1;
lv_obj_t * ui_lblHeight2;
lv_obj_t * ui_Label34;
void ui_event_TextAreaEmptyTank(lv_event_t * e);
lv_obj_t * ui_TextAreaEmptyTank;
void ui_event_TextAreaFullTank(lv_event_t * e);
lv_obj_t * ui_TextAreaFullTank;
lv_obj_t * ui_ContButtons;
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label36;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label37;
lv_obj_t * ui_lblSaved;
void ui_event_ParamKeyboard(lv_event_t * e);
lv_obj_t * ui_ParamKeyboard;
lv_obj_t * ui_Settings;
lv_obj_t * ui_Container2;
lv_obj_t * ui_lblWifiSwitch;
void ui_event_btnWifi(lv_event_t * e);
lv_obj_t * ui_btnWifi;
lv_obj_t * ui_Label5;
void ui_event_btnMQTT(lv_event_t * e);
lv_obj_t * ui_btnMQTT;
lv_obj_t * ui_Label30;
lv_obj_t * ui_ContDarkMode;
lv_obj_t * ui_lblDarkMode;
void ui_event_Switch2(lv_event_t * e);
lv_obj_t * ui_Switch2;
lv_obj_t * ui_ContBackLigth;
lv_obj_t * ui_lblBackLight;
void ui_event_switchManualAutomatic(lv_event_t * e);
lv_obj_t * ui_switchManualAutomatic;
lv_obj_t * ui_Label6;
lv_obj_t * ui_lblLigthSensorValue;
void ui_event_LigthSensorSlider(lv_event_t * e);
lv_obj_t * ui_LigthSensorSlider;
lv_obj_t * ui_lblLigthSensorSliderValue;
lv_obj_t * ui_ContLanguage;
lv_obj_t * ui_lblLanguage;
lv_obj_t * ui_DropdownLanguage;
lv_obj_t * ui_ContRotateScreen;
lv_obj_t * ui_lblrotate;
void ui_event_btnRotate(lv_event_t * e);
lv_obj_t * ui_btnRotate;
lv_obj_t * ui_Label7;
lv_obj_t * ui_ContSWReset;
lv_obj_t * ui_lblrotate1;
void ui_event_btnReset(lv_event_t * e);
lv_obj_t * ui_btnReset;
lv_obj_t * ui_Label29;
lv_obj_t * ui_About;
lv_obj_t * ui_ConBuildDate;
lv_obj_t * ui_lblBuildDate;
lv_obj_t * ui_lblBuildDateValue;
lv_obj_t * ui_ConBuildVersion;
lv_obj_t * ui_lblBuildVersion;
lv_obj_t * ui_lblBuildVersionValue;
void ui_event_btnFWUpdate(lv_event_t * e);
lv_obj_t * ui_btnFWUpdate;
lv_obj_t * ui_Label38;
lv_obj_t * ui_ConRunTime;
lv_obj_t * ui_lblRunTime;
lv_obj_t * ui_lblRunTimeValue;
lv_obj_t * ui_ConGitHub;
lv_obj_t * ui_lblGit;
lv_obj_t * ui_lblGitHub;
lv_obj_t * ui_ConAuth;
lv_obj_t * ui_lblGit1;
lv_obj_t * ui_lblGitHub1;
lv_obj_t * ui_ConPayPall;
lv_obj_t * ui_lblGit2;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
lv_obj_t * ui_lblPaypall;
lv_obj_t * ui_Image1;


// SCREEN: ui_Wifi_Settings
void ui_Wifi_Settings_screen_init(void);
lv_obj_t * ui_Wifi_Settings;
lv_obj_t * ui_TopInfoBar2;
lv_obj_t * ui_Spinner4;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Container9;
lv_obj_t * ui_Label4;
lv_obj_t * ui_lblWifiStatus;
lv_obj_t * ui_Container10;
lv_obj_t * ui_Label15;
lv_obj_t * ui_lblWifiSSID;
lv_obj_t * ui_Container11;
lv_obj_t * ui_Label17;
lv_obj_t * ui_lblWifiIP;
lv_obj_t * ui_Container12;
lv_obj_t * ui_Label20;
lv_obj_t * ui_lblWifiRSSI;
lv_obj_t * ui_Container13;
lv_obj_t * ui_Label22;
lv_obj_t * ui_lblWifiChannel;
lv_obj_t * ui_Container14;
lv_obj_t * ui_Label24;
lv_obj_t * ui_lblWifiSecurity;
lv_obj_t * ui_Container16;
lv_obj_t * ui_Label27;
lv_obj_t * ui_lblTime;
lv_obj_t * ui_lblTimeZone;
void ui_event_btnScanWifi(lv_event_t * e);
lv_obj_t * ui_btnScanWifi;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Container15;
lv_obj_t * ui_Label14;
void ui_event_btnForgetWifi(lv_event_t * e);
lv_obj_t * ui_btnForgetWifi;
lv_obj_t * ui_Label25;
void ui_event_btnBack(lv_event_t * e);
lv_obj_t * ui_btnBack;
lv_obj_t * ui_Label28;


// SCREEN: ui_WifiScanResult
void ui_WifiScanResult_screen_init(void);
lv_obj_t * ui_WifiScanResult;
lv_obj_t * ui_TopInfoBar5;
lv_obj_t * ui_Spinner6;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Label1;
void ui_event_funcWifiScan(lv_event_t * e);
lv_obj_t * ui_funcWifiScan;
lv_obj_t * ui_Label2;
void ui_event_btnback(lv_event_t * e);
lv_obj_t * ui_btnback;
lv_obj_t * ui_Label19;
lv_obj_t * ui_PanelWifiList;
lv_obj_t * ui_Label3;
lv_obj_t * ui_panelScanningWifi;
lv_obj_t * ui_Label26;


// SCREEN: ui_ConnectToWifi
void ui_ConnectToWifi_screen_init(void);
lv_obj_t * ui_ConnectToWifi;
lv_obj_t * ui_TopInfoBar3;
lv_obj_t * ui_Spinner3;
void ui_event_Keyboard1(lv_event_t * e);
lv_obj_t * ui_Keyboard1;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Label8;
lv_obj_t * ui_lblWifiSSIDToBeConnect;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Label10;
lv_obj_t * ui_textareaWifiPassword;
lv_obj_t * ui_Container7;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label12;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label13;
lv_obj_t * ui_panelConnectionSuccess;
lv_obj_t * ui_Label16;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label18;
lv_obj_t * ui_panelNotConnected;
lv_obj_t * ui_Label21;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label23;
lv_obj_t * ui_panelConnectingToWifi;
lv_obj_t * ui_Label9;
lv_obj_t * ui_lblAttemptNumber;


// SCREEN: ui_MQTTSettings
void ui_MQTTSettings_screen_init(void);
lv_obj_t * ui_MQTTSettings;
lv_obj_t * ui_TopInfoBar;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_ContMQTTServer;
lv_obj_t * ui_lblMQTTlbl;
void ui_event_TextAreaMQTTServer(lv_event_t * e);
lv_obj_t * ui_TextAreaMQTTServer;
lv_obj_t * ui_ContMQTTUser;
lv_obj_t * ui_lblMQTTuser;
void ui_event_TextAreaMQTTuser(lv_event_t * e);
lv_obj_t * ui_TextAreaMQTTuser;
lv_obj_t * ui_ContMQTTPassword;
lv_obj_t * ui_lblMQTTPassword;
void ui_event_TextAreaMQTTPassword(lv_event_t * e);
lv_obj_t * ui_TextAreaMQTTPassword;
void ui_event_Back(lv_event_t * e);
lv_obj_t * ui_Back;
lv_obj_t * ui_lblBack;
void ui_event_Save(lv_event_t * e);
lv_obj_t * ui_Save;
lv_obj_t * ui_lblBack1;
void ui_event_Forget(lv_event_t * e);
lv_obj_t * ui_Forget;
lv_obj_t * ui_lblBack2;
void ui_event_KeyboardMQTT(lv_event_t * e);
lv_obj_t * ui_KeyboardMQTT;
lv_obj_t * ui____initial_actions0;
const lv_image_dsc_t * ui_imgset_qrcode_[1] = {&ui_img_qrcode_2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        funcResetMinMaxDistance(e);
    }
}
void ui_event_DropdownParamTankType(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        funcTankTypeChanged(e);
    }
}
void ui_event_TextAreaRectangleWide(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_ParamKeyboard,  ui_TextAreaRectangleWide);
        _ui_flag_modify(ui_ParamKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        funcParamRectangleWide(e);
    }
}
void ui_event_TextAreaRectangleDepth(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_ParamKeyboard,  ui_TextAreaRectangleDepth);
        _ui_flag_modify(ui_ParamKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        funcParamRectangleDepth(e);
    }
}
void ui_event_TextAreaRectangleHeight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_ParamKeyboard,  ui_TextAreaRectangleHeight);
        _ui_flag_modify(ui_ParamKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        funcParamRectangleHeight(e);
    }
}
void ui_event_TextAreaCilinderDiameter(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_ParamKeyboard,  ui_TextAreaCilinderDiameter);
        _ui_flag_modify(ui_ParamKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        funcParamCilinderDiameter(e);
    }
}
void ui_event_TextAreaCilinderHeight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_ParamKeyboard,  ui_TextAreaCilinderHeight);
        _ui_flag_modify(ui_ParamKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        funcParamCilinderHeight(e);
    }
}
void ui_event_TextAreaEmptyTank(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_ParamKeyboard,  ui_TextAreaEmptyTank);
        _ui_flag_modify(ui_ParamKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        funcParamEmptyTank(e);
    }
}
void ui_event_TextAreaFullTank(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_ParamKeyboard,  ui_TextAreaFullTank);
        _ui_flag_modify(ui_ParamKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        funcParamFullTank(e);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        funcParamSave(e);
    }
}
void ui_event_ParamKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        funcParamKeyboardOk(e);
    }
}
void ui_event_btnWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Wifi_Settings, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Wifi_Settings_screen_init);
    }
}
void ui_event_btnMQTT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MQTTSettings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_MQTTSettings_screen_init);
    }
}
void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_DARK_MODE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_DEFAULT);
    }
}
void ui_event_switchManualAutomatic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        funcBackLightButton(e);
    }
}
void ui_event_LigthSensorSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_lblLigthSensorSliderValue, target, "", "%");
    }
}
void ui_event_btnRotate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        funcRotateScreen(e);
    }
}
void ui_event_btnReset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        funcSWReset(e);
    }
}
void ui_event_btnFWUpdate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        funcCheckFW(e);
    }
}
void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_ConBuildDate, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_ConBuildVersion, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_ConRunTime, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_ConGitHub, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_ConAuth, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_btnScanWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiScanResult, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_WifiScanResult_screen_init);
    }
}
void ui_event_btnForgetWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        funcResetWifi(e);
    }
}
void ui_event_btnBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Main_Screen_screen_init);
    }
}
void ui_event_funcWifiScan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        funcWifiScan(e);
    }
}
void ui_event_btnback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Wifi_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Wifi_Settings_screen_init);
    }
}
void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_textareaWifiPassword);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        funcConnectToWifiButtonPress(e);
    }
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiScanResult, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_WifiScanResult_screen_init);
    }
}
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Wifi_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Wifi_Settings_screen_init);
        _ui_flag_modify(ui_panelConnectionSuccess, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_panelNotConnected, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        funcRetryButtonWrongPassword(e);
    }
}
void ui_event_TextAreaMQTTServer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardMQTT,  ui_TextAreaMQTTServer);
        _ui_flag_modify(ui_KeyboardMQTT, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_TextAreaMQTTuser(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardMQTT,  ui_TextAreaMQTTuser);
        _ui_flag_modify(ui_KeyboardMQTT, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_TextAreaMQTTPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardMQTT,  ui_TextAreaMQTTPassword);
        _ui_flag_modify(ui_KeyboardMQTT, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_Back(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main_Screen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Main_Screen_screen_init);
    }
}
void ui_event_Save(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        funcSaveMQTTCredentials(e);
    }
}
void ui_event_Forget(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        funcForgetMQTTSettings(e);
    }
}
void ui_event_KeyboardMQTT(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_KeyboardMQTT, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Main_Screen_screen_init();
    ui_Wifi_Settings_screen_init();
    ui_WifiScanResult_screen_init();
    ui_ConnectToWifi_screen_init();
    ui_MQTTSettings_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Main_Screen);
}
