// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: WaterTank

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void funcResetMinMaxDistance(lv_event_t * e);
void funcTankTypeChanged(lv_event_t * e);
void funcParamRectangleWide(lv_event_t * e);
void funcParamRectangleDepth(lv_event_t * e);
void funcParamRectangleHeight(lv_event_t * e);
void funcParamCilinderDiameter(lv_event_t * e);
void funcParamCilinderHeight(lv_event_t * e);
void funcParamEmptyTank(lv_event_t * e);
void funcParamFullTank(lv_event_t * e);
void funcParamSave(lv_event_t * e);
void funcParamKeyboardOk(lv_event_t * e);
void funcBackLightButton(lv_event_t * e);
void funcRotateScreen(lv_event_t * e);
void funcSWReset(lv_event_t * e);
void funcCheckFW(lv_event_t * e);
void funcResetWifi(lv_event_t * e);
void funcWifiScan(lv_event_t * e);
void funcConnectToWifiButtonPress(lv_event_t * e);
void funcRetryButtonWrongPassword(lv_event_t * e);
void funcSaveMQTTCredentials(lv_event_t * e);
void funcForgetMQTTSettings(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
