// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: WaterTank

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void funcResetWifi(lv_event_t * e);
void funcWifiScan(lv_event_t * e);
void ConnectToWifiButtonPress(lv_event_t * e);
void RetryButtonWrongPassword(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
