// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: WaterTank

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_BackGround[2] = {0xFFFFFF, 0x373737};
const ui_theme_variable_t _ui_theme_alpha_BackGround[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_FontColor[2] = {0x000000, 0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_FontColor[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_Border[2] = {0x2C2C2C, 0xB1B1B1};
const ui_theme_variable_t _ui_theme_alpha_Border[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_DARK_MODE;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

