// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: WaterTank

#include "../ui.h"

void ui_Info_screen_init(void)
{
    ui_Info = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Info, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_Info, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_Info);

    ui_TopInfoBar6 = lv_obj_create(ui_Info);
    lv_obj_remove_style_all(ui_TopInfoBar6);
    lv_obj_set_width(ui_TopInfoBar6, 318);
    lv_obj_set_height(ui_TopInfoBar6, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_TopInfoBar6, 1);
    lv_obj_set_y(ui_TopInfoBar6, 1);
    lv_obj_remove_flag(ui_TopInfoBar6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_TopInfoBar6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackGround);
    ui_object_set_themeable_style_property(ui_TopInfoBar6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackGround);
    ui_object_set_themeable_style_property(ui_TopInfoBar6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_TopInfoBar6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_TopInfoBar6, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner7 = lv_spinner_create(ui_TopInfoBar6);
    //lv_spinner_set_anim_params(ui_Spinner7, 1000, 90);
    lv_obj_set_width(ui_Spinner7, 20);
    lv_obj_set_height(ui_Spinner7, 20);
    lv_obj_set_align(ui_Spinner7, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_Spinner7, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner7, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Spinner7, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Info);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 318);
    lv_obj_set_height(ui_Container8, 217);
    lv_obj_set_x(ui_Container8, 1);
    lv_obj_set_y(ui_Container8, 22);
    lv_obj_remove_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9 = lv_button_create(ui_Container8);
    lv_obj_set_width(ui_Button9, 80);
    lv_obj_set_height(ui_Button9, 25);
    lv_obj_set_x(ui_Button9, -5);
    lv_obj_set_y(ui_Button9, -5);
    lv_obj_set_align(ui_Button9, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_Button9);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "Back");

    ui_Button10 = lv_button_create(ui_Container8);
    lv_obj_set_width(ui_Button10, 30);
    lv_obj_set_height(ui_Button10, 25);
    lv_obj_set_x(ui_Button10, -190);
    lv_obj_set_y(ui_Button10, -10);
    lv_obj_set_align(ui_Button10, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label40 = lv_label_create(ui_Button10);
    lv_obj_set_width(ui_Label40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label40, ">");

    ui_Button11 = lv_button_create(ui_Container8);
    lv_obj_set_width(ui_Button11, 30);
    lv_obj_set_height(ui_Button11, 25);
    lv_obj_set_x(ui_Button11, -257);
    lv_obj_set_y(ui_Button11, -10);
    lv_obj_set_align(ui_Button11, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label41 = lv_label_create(ui_Button11);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "<");

    lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);

}
