// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: WaterTank

#include "../ui.h"

void ui_Main_Screen_screen_init(void)
{
    ui_Main_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Main_Screen, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TopInfoBar1 = lv_obj_create(ui_Main_Screen);
    lv_obj_remove_style_all(ui_TopInfoBar1);
    lv_obj_set_width(ui_TopInfoBar1, 318);
    lv_obj_set_height(ui_TopInfoBar1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_TopInfoBar1, 1);
    lv_obj_set_y(ui_TopInfoBar1, 1);
    lv_obj_remove_flag(ui_TopInfoBar1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_TopInfoBar1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackGround);
    ui_object_set_themeable_style_property(ui_TopInfoBar1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackGround);
    ui_object_set_themeable_style_property(ui_TopInfoBar1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_TopInfoBar1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_TopInfoBar1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner2 = lv_spinner_create(ui_TopInfoBar1);
    //lv_spinner_set_anim_params(ui_Spinner2, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 20);
    lv_obj_set_height(ui_Spinner2, 20);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Spinner2, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_imWifiInternetOK1 = lv_image_create(ui_TopInfoBar1);
    lv_image_set_src(ui_imWifiInternetOK1, &ui_img_wifiinternetok_png);
    lv_obj_set_width(ui_imWifiInternetOK1, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_imWifiInternetOK1, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_imWifiInternetOK1, 20);
    lv_obj_set_y(ui_imWifiInternetOK1, 0);
    lv_obj_set_align(ui_imWifiInternetOK1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_imWifiInternetOK1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imWifiInternetOK1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imWifiDisconnected1 = lv_image_create(ui_TopInfoBar1);
    lv_image_set_src(ui_imWifiDisconnected1, &ui_img_wifidisconnected_png);
    lv_obj_set_width(ui_imWifiDisconnected1, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_imWifiDisconnected1, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_imWifiDisconnected1, 20);
    lv_obj_set_y(ui_imWifiDisconnected1, 0);
    lv_obj_set_align(ui_imWifiDisconnected1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_imWifiDisconnected1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imWifiDisconnected1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imWifiConnectedNoInternet1 = lv_image_create(ui_TopInfoBar1);
    lv_image_set_src(ui_imWifiConnectedNoInternet1, &ui_img_wificonnectednointernet_png);
    lv_obj_set_width(ui_imWifiConnectedNoInternet1, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_imWifiConnectedNoInternet1, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_imWifiConnectedNoInternet1, 20);
    lv_obj_set_y(ui_imWifiConnectedNoInternet1, 0);
    lv_obj_set_align(ui_imWifiConnectedNoInternet1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_imWifiConnectedNoInternet1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imWifiConnectedNoInternet1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblDataNTime = lv_label_create(ui_TopInfoBar1);
    lv_obj_set_width(ui_lblDataNTime, lv_pct(49));
    lv_obj_set_height(ui_lblDataNTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDataNTime, -20);
    lv_obj_set_y(ui_lblDataNTime, 0);
    lv_obj_set_align(ui_lblDataNTime, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lblDataNTime, "2025.04.10 11:17:32");
    lv_obj_set_style_text_align(ui_lblDataNTime, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDataNTime, &ui_font_DejaVuSansMono14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWifiRSSI2 = lv_label_create(ui_TopInfoBar1);
    lv_obj_set_width(ui_lblWifiRSSI2, 75);
    lv_obj_set_height(ui_lblWifiRSSI2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblWifiRSSI2, 40);
    lv_obj_set_y(ui_lblWifiRSSI2, 1);
    lv_obj_set_align(ui_lblWifiRSSI2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblWifiRSSI2, "-102 dBm");
    lv_obj_set_style_text_align(ui_lblWifiRSSI2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainTabView = lv_tabview_create(ui_Main_Screen);
    lv_tabview_set_tab_bar_size(ui_MainTabView, 30);
    lv_obj_set_width(ui_MainTabView, 318);
    lv_obj_set_height(ui_MainTabView, 217);
    lv_obj_set_x(ui_MainTabView, 0);
    lv_obj_set_y(ui_MainTabView, 22);
    lv_obj_set_align(ui_MainTabView, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MainTabView, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    ui_object_set_themeable_style_property(ui_MainTabView, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackGround);
    ui_object_set_themeable_style_property(ui_MainTabView, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackGround);
    ui_object_set_themeable_style_property(ui_MainTabView, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_MainTabView, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_MainTabView, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_MainTabView),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_MainTabView),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_OPA, _ui_theme_alpha_FontColor);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_MainTabView),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_BackGround);
    ui_object_set_themeable_style_property(lv_tabview_get_tab_bar(ui_MainTabView),  LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_OPA, _ui_theme_alpha_BackGround);
    lv_obj_set_style_border_color(lv_tabview_get_tab_bar(ui_MainTabView), lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_bar(ui_MainTabView), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_tabview_get_tab_bar(ui_MainTabView), 1,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(lv_tabview_get_tab_bar(ui_MainTabView), LV_BORDER_SIDE_BOTTOM,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Main = lv_tabview_add_tab(ui_MainTabView, "Main");
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    ui_object_set_themeable_style_property(ui_Main, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackGround);
    ui_object_set_themeable_style_property(ui_Main, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackGround);
    lv_obj_set_style_pad_left(ui_Main, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Main, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Main, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Main, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBar = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_PanelBar, 235);
    lv_obj_set_height(ui_PanelBar, 46);
    lv_obj_set_x(ui_PanelBar, 3);
    lv_obj_set_y(ui_PanelBar, -1);
    lv_obj_remove_flag(ui_PanelBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarCurrentState = lv_bar_create(ui_PanelBar);
    lv_bar_set_range(ui_BarCurrentState, 0, 4500);
    lv_bar_set_value(ui_BarCurrentState, 2000, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BarCurrentState, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_BarCurrentState, 15);
    lv_obj_set_width(ui_BarCurrentState, lv_pct(100));
    lv_obj_set_x(ui_BarCurrentState, 0);
    lv_obj_set_y(ui_BarCurrentState, -10);
    lv_obj_set_align(ui_BarCurrentState, LV_ALIGN_TOP_MID);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_BarCurrentState, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_BarCurrentState,
                                                                                                      lv_obj_get_style_pad_right(ui_BarCurrentState, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_lblCurrentLiter1 = lv_label_create(ui_BarCurrentState);
    lv_obj_set_width(ui_lblCurrentLiter1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCurrentLiter1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblCurrentLiter1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCurrentLiter1, "?%");
    ui_object_set_themeable_style_property(ui_lblCurrentLiter1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblCurrentLiter1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblMaxValue = lv_label_create(ui_PanelBar);
    lv_obj_set_width(ui_lblMaxValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMaxValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMaxValue, 10);
    lv_obj_set_y(ui_lblMaxValue, 10);
    lv_obj_set_align(ui_lblMaxValue, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_lblMaxValue, "4500L");
    lv_obj_add_flag(ui_lblMaxValue, LV_OBJ_FLAG_HIDDEN);     /// Flags
    ui_object_set_themeable_style_property(ui_lblMaxValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblMaxValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblMinValue = lv_label_create(ui_PanelBar);
    lv_obj_set_width(ui_lblMinValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMinValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMinValue, -10);
    lv_obj_set_y(ui_lblMinValue, 10);
    lv_label_set_text(ui_lblMinValue, "0");
    lv_obj_add_flag(ui_lblMinValue, LV_OBJ_FLAG_HIDDEN);     /// Flags
    ui_object_set_themeable_style_property(ui_lblMinValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblMinValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblMax = lv_label_create(ui_PanelBar);
    lv_obj_set_width(ui_lblMax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMax, -79);
    lv_obj_set_y(ui_lblMax, 7);
    lv_obj_set_align(ui_lblMax, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMax, "Max");
    lv_obj_add_flag(ui_lblMax, LV_OBJ_FLAG_HIDDEN);     /// Flags
    ui_object_set_themeable_style_property(ui_lblMax, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblMax, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblMin = lv_label_create(ui_PanelBar);
    lv_obj_set_width(ui_lblMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMin, -80);
    lv_obj_set_y(ui_lblMin, -14);
    lv_obj_set_align(ui_lblMin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMin, "Min");
    lv_obj_add_flag(ui_lblMin, LV_OBJ_FLAG_HIDDEN);     /// Flags
    ui_object_set_themeable_style_property(ui_lblMin, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblMin, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_Panel3 = lv_obj_create(ui_PanelBar);
    lv_obj_set_height(ui_Panel3, 23);
    lv_obj_set_width(ui_Panel3, lv_pct(65));
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 10);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblCurrentLiter = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_lblCurrentLiter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCurrentLiter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblCurrentLiter, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCurrentLiter, "1555L / 4500L");
    ui_object_set_themeable_style_property(ui_lblCurrentLiter, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblCurrentLiter, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_THPanel = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_THPanel, 63);
    lv_obj_set_height(ui_THPanel, 46);
    lv_obj_set_align(ui_THPanel, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_THPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_THPanel, lv_color_hex(0x10CFA1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_THPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_THPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_THPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_THPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_THPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_THPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_THPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_THPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTempValue = lv_label_create(ui_THPanel);
    lv_obj_set_width(ui_lblTempValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTempValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblTempValue, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lblTempValue, "00,0 C°");
    ui_object_set_themeable_style_property(ui_lblTempValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblTempValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);
    lv_obj_set_style_text_align(ui_lblTempValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHumValue = lv_label_create(ui_THPanel);
    lv_obj_set_width(ui_lblHumValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHumValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblHumValue, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lblHumValue, "00,0 %");
    ui_object_set_themeable_style_property(ui_lblHumValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblHumValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);
    lv_obj_set_style_text_align(ui_lblHumValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart2 = lv_chart_create(ui_Main);
    lv_obj_set_width(ui_Chart2, 266);
    lv_obj_set_height(ui_Chart2, 100);
    lv_obj_set_x(ui_Chart2, 18);
    lv_obj_set_y(ui_Chart2, 17);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_Chart2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Chart2, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart2, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 0, 2000);
    lv_chart_set_div_line_count(ui_Chart2, 5, 5);
    ui_object_set_themeable_style_property(ui_Chart2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Chart2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Border);
    ui_object_set_themeable_style_property(ui_Chart2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Chart2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);

    ui_Chart2_Xaxis = lv_scale_create(ui_Chart2);
    lv_scale_set_mode(ui_Chart2_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart2_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart2_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart2_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart2,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart2, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart2_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart2_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart2_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart2_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart2_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart2_Xaxis, 0, 13 > 0 ? 13 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart2_Xaxis, (13 > 0 ? 13 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart2_Xaxis, 2 >= 1 ? 2 : 1);
    ui_Chart2_Yaxis1 = lv_scale_create(ui_Chart2);
    lv_scale_set_mode(ui_Chart2_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart2_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Chart2_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart2_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart2,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart2, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart2_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart2_Yaxis1, 5, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_Chart2_Yaxis1,  0, 2000);
    lv_scale_set_total_tick_count(ui_Chart2_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart2_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_Chart2_Yaxis2 = lv_scale_create(ui_Chart2);
    lv_scale_set_mode(ui_Chart2_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart2_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart2_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart2_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart2,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart2, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart2_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart2_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart2_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_Chart2_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart2_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_Chart2_Yaxis2, false);
    lv_chart_series_t * ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);


    ui_object_set_themeable_style_property(ui_Chart2_Xaxis, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_Chart2_Xaxis, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);
    ui_object_set_themeable_style_property(ui_Chart2_Yaxis1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_Chart2_Yaxis1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);
    ui_object_set_themeable_style_property(ui_Chart2_Yaxis2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_Chart2_Yaxis2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart2, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart2, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_lblL = lv_label_create(ui_Main);
    lv_obj_set_width(ui_lblL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblL, -147);
    lv_obj_set_y(ui_lblL, 61);
    lv_obj_set_align(ui_lblL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblL, "[L]");
    ui_object_set_themeable_style_property(ui_lblL, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblL, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_ChartActualLiter = lv_chart_create(ui_Main);
    lv_obj_set_width(ui_ChartActualLiter, 231);
    lv_obj_set_height(ui_ChartActualLiter, 110);
    lv_obj_set_x(ui_ChartActualLiter, 6);
    lv_obj_set_y(ui_ChartActualLiter, 17);
    lv_obj_set_align(ui_ChartActualLiter, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChartActualLiter, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_ChartActualLiter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_ChartActualLiter,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_ChartActualLiter, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_ChartActualLiter, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_ChartActualLiter, 30);
    lv_chart_set_range(ui_ChartActualLiter, LV_CHART_AXIS_PRIMARY_Y, 0, 3200);
    lv_chart_set_div_line_count(ui_ChartActualLiter, 5, 7);

    ui_ChartActualLiter_Xaxis = lv_scale_create(ui_ChartActualLiter);
    lv_scale_set_mode(ui_ChartActualLiter_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_ChartActualLiter_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_ChartActualLiter_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_ChartActualLiter_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_ChartActualLiter,
                                                                             LV_PART_MAIN) + lv_obj_get_style_border_width(ui_ChartActualLiter, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_ChartActualLiter_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ChartActualLiter_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_ChartActualLiter_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ChartActualLiter_Xaxis, 1, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_ChartActualLiter_Xaxis, 3, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_ChartActualLiter_Xaxis, 0, 13 > 0 ? 13 - 1 : 0);
    lv_scale_set_total_tick_count(ui_ChartActualLiter_Xaxis, (13 > 0 ? 13 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_ChartActualLiter_Xaxis, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_ChartActualLiter_Xaxis, false);
    ui_ChartActualLiter_Yaxis1 = lv_scale_create(ui_ChartActualLiter);
    lv_scale_set_mode(ui_ChartActualLiter_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_ChartActualLiter_Yaxis1, 30, lv_pct(100));
    lv_obj_set_align(ui_ChartActualLiter_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_ChartActualLiter_Yaxis1, -30 - lv_obj_get_style_pad_left(ui_ChartActualLiter,
                                                                             LV_PART_MAIN) - lv_obj_get_style_border_width(ui_ChartActualLiter, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_ChartActualLiter_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ChartActualLiter_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_ChartActualLiter_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ChartActualLiter_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_ChartActualLiter_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_ChartActualLiter_Yaxis1,  0, 3200);
    lv_scale_set_total_tick_count(ui_ChartActualLiter_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_ChartActualLiter_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_ChartActualLiter_Yaxis2 = lv_scale_create(ui_ChartActualLiter);
    lv_scale_set_mode(ui_ChartActualLiter_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_ChartActualLiter_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_ChartActualLiter_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_ChartActualLiter_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_ChartActualLiter,
                                                                             LV_PART_MAIN) + lv_obj_get_style_border_width(ui_ChartActualLiter, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_ChartActualLiter_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ChartActualLiter_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_ChartActualLiter_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ChartActualLiter_Yaxis2, 3, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_ChartActualLiter_Yaxis2, 5, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_ChartActualLiter_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_ChartActualLiter_Yaxis2, 2 >= 1 ? 2 : 1);



    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_ChartActualLiter, LV_MAX3(50, 30, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_ChartActualLiter, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_lblH1 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_lblH1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblH1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblH1, -119);
    lv_obj_set_y(ui_lblH1, 82);
    lv_obj_set_align(ui_lblH1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblH1, "[h]");
    ui_object_set_themeable_style_property(ui_lblH1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblH1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblPer = lv_label_create(ui_Main);
    lv_obj_set_width(ui_lblPer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPer, 148);
    lv_obj_set_y(ui_lblPer, 60);
    lv_obj_set_align(ui_lblPer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPer, "[%]");
    ui_object_set_themeable_style_property(ui_lblPer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblPer, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_Statistic = lv_tabview_add_tab(ui_MainTabView, "Statistic");
    lv_obj_set_flex_flow(ui_Statistic, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Statistic, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Statistic, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_pad_left(ui_Statistic, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Statistic, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Statistic, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Statistic, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Statistic);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_height(ui_Container5, 45);
    lv_obj_set_width(ui_Container5, lv_pct(100));
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container5, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Container5);
    lv_obj_set_height(ui_Panel2, 29);
    lv_obj_set_width(ui_Panel2, lv_pct(30));
    lv_obj_set_x(ui_Panel2, 5);
    lv_obj_set_y(ui_Panel2, 2);
    lv_obj_add_flag(ui_Panel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblActualDistance = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_lblActualDistance, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblActualDistance, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblActualDistance, 10);
    lv_obj_set_y(ui_lblActualDistance, 25);
    lv_label_set_text(ui_lblActualDistance, "Actual:");

    ui_lblActualDistanceValue = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_lblActualDistanceValue, 80);
    lv_obj_set_height(ui_lblActualDistanceValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblActualDistanceValue, 60);
    lv_obj_set_y(ui_lblActualDistanceValue, 25);
    lv_label_set_text(ui_lblActualDistanceValue, "1500 mm");
    lv_obj_set_style_text_align(ui_lblActualDistanceValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMinDistance = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_lblMinDistance, 40);
    lv_obj_set_height(ui_lblMinDistance, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMinDistance, 170);
    lv_obj_set_y(ui_lblMinDistance, 5);
    lv_label_set_text(ui_lblMinDistance, "Min:");

    ui_lblMinDistanceValue = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_lblMinDistanceValue, 80);
    lv_obj_set_height(ui_lblMinDistanceValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMinDistanceValue, 210);
    lv_obj_set_y(ui_lblMinDistanceValue, 5);
    lv_label_set_text(ui_lblMinDistanceValue, "1000 mm");
    lv_obj_set_style_text_align(ui_lblMinDistanceValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMaxDistance = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_lblMaxDistance, 40);
    lv_obj_set_height(ui_lblMaxDistance, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMaxDistance, 170);
    lv_obj_set_y(ui_lblMaxDistance, 25);
    lv_label_set_text(ui_lblMaxDistance, "Max:");

    ui_lblMaxDistanceValue = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_lblMaxDistanceValue, 80);
    lv_obj_set_height(ui_lblMaxDistanceValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMaxDistanceValue, 210);
    lv_obj_set_y(ui_lblMaxDistanceValue, 25);
    lv_label_set_text(ui_lblMaxDistanceValue, "9999 mm");
    lv_obj_set_style_text_align(ui_lblMaxDistanceValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDistance = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_lblDistance, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDistance, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDistance, 10);
    lv_obj_set_y(ui_lblDistance, 5);
    lv_label_set_text(ui_lblDistance, "Distance");
    lv_obj_set_style_text_decor(ui_lblDistance, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_Container5);
    lv_obj_set_width(ui_Button1, 69);
    lv_obj_set_height(ui_Button1, 20);
    lv_obj_set_x(ui_Button1, 86);
    lv_obj_set_y(ui_Button1, 3);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label31 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Reset");

    ui_Param = lv_tabview_add_tab(ui_MainTabView, "Param");
    lv_obj_set_flex_flow(ui_Param, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Param, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Param, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_pad_left(ui_Param, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Param, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Param, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Param, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Param, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Param, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContTankType = lv_obj_create(ui_Param);
    lv_obj_remove_style_all(ui_ContTankType);
    lv_obj_set_height(ui_ContTankType, 30);
    lv_obj_set_width(ui_ContTankType, lv_pct(100));
    lv_obj_set_align(ui_ContTankType, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContTankType, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContTankType, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContTankType, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContTankType, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContTankType, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContTankType, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContTankType, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContTankType, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContTankType, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_ContTankType);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label32, "Tank Type");
    lv_obj_set_style_pad_left(ui_Label32, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label32, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label32, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label32, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownParamTankType = lv_dropdown_create(ui_ContTankType);
    lv_dropdown_set_options(ui_DropdownParamTankType, "Cilinder\nRectangle");
    lv_obj_set_width(ui_DropdownParamTankType, 150);
    lv_obj_set_height(ui_DropdownParamTankType, 25);
    lv_obj_set_align(ui_DropdownParamTankType, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_DropdownParamTankType, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_pad_left(ui_DropdownParamTankType, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DropdownParamTankType, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DropdownParamTankType, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DropdownParamTankType, 3, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ContRectangle = lv_obj_create(ui_Param);
    lv_obj_remove_style_all(ui_ContRectangle);
    lv_obj_set_height(ui_ContRectangle, 67);
    lv_obj_set_width(ui_ContRectangle, lv_pct(100));
    lv_obj_set_x(ui_ContRectangle, 0);
    lv_obj_set_y(ui_ContRectangle, -10);
    lv_obj_set_align(ui_ContRectangle, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContRectangle, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_ContRectangle, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContRectangle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContRectangle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContRectangle, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContRectangle, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContRectangle, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContRectangle, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContRectangle, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContRectangle, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWide = lv_label_create(ui_ContRectangle);
    lv_obj_set_width(ui_lblWide, 100);
    lv_obj_set_height(ui_lblWide, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblWide, 80);
    lv_obj_set_y(ui_lblWide, 0);
    lv_label_set_text(ui_lblWide, "Wide[mm]:");
    lv_obj_set_style_text_align(ui_lblWide, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDepth = lv_label_create(ui_ContRectangle);
    lv_obj_set_width(ui_lblDepth, 100);
    lv_obj_set_height(ui_lblDepth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDepth, 80);
    lv_obj_set_y(ui_lblDepth, 20);
    lv_label_set_text(ui_lblDepth, "Depth[mm]:");
    lv_obj_set_style_text_align(ui_lblDepth, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHeight = lv_label_create(ui_ContRectangle);
    lv_obj_set_width(ui_lblHeight, 100);
    lv_obj_set_height(ui_lblHeight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblHeight, 80);
    lv_obj_set_y(ui_lblHeight, 40);
    lv_label_set_text(ui_lblHeight, "Height[mm]:");
    lv_obj_set_style_text_align(ui_lblHeight, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_ContRectangle);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label35, "Rectangle");

    ui_TextAreaRectangleWide = lv_textarea_create(ui_ContRectangle);
    lv_obj_set_width(ui_TextAreaRectangleWide, 110);
    lv_obj_set_height(ui_TextAreaRectangleWide, 20);
    lv_obj_set_x(ui_TextAreaRectangleWide, 189);
    lv_obj_set_y(ui_TextAreaRectangleWide, 0);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_TextAreaRectangleWide, NULL);
    else lv_textarea_set_accepted_chars(ui_TextAreaRectangleWide, "0123456789");
    lv_textarea_set_placeholder_text(ui_TextAreaRectangleWide, "1-9999");
    lv_obj_set_style_pad_left(ui_TextAreaRectangleWide, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextAreaRectangleWide, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TextAreaRectangleWide, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TextAreaRectangleWide, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TextAreaRectangleDepth = lv_textarea_create(ui_ContRectangle);
    lv_obj_set_width(ui_TextAreaRectangleDepth, 110);
    lv_obj_set_height(ui_TextAreaRectangleDepth, 20);
    lv_obj_set_x(ui_TextAreaRectangleDepth, 189);
    lv_obj_set_y(ui_TextAreaRectangleDepth, 20);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_TextAreaRectangleDepth, NULL);
    else lv_textarea_set_accepted_chars(ui_TextAreaRectangleDepth, "0123456789");
    lv_textarea_set_placeholder_text(ui_TextAreaRectangleDepth, "1-9999");
    lv_obj_set_style_pad_left(ui_TextAreaRectangleDepth, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextAreaRectangleDepth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TextAreaRectangleDepth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TextAreaRectangleDepth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TextAreaRectangleHeight = lv_textarea_create(ui_ContRectangle);
    lv_obj_set_width(ui_TextAreaRectangleHeight, 110);
    lv_obj_set_height(ui_TextAreaRectangleHeight, 20);
    lv_obj_set_x(ui_TextAreaRectangleHeight, 189);
    lv_obj_set_y(ui_TextAreaRectangleHeight, 40);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_TextAreaRectangleHeight, NULL);
    else lv_textarea_set_accepted_chars(ui_TextAreaRectangleHeight, "0123456789");
    lv_textarea_set_placeholder_text(ui_TextAreaRectangleHeight, "1-9999");
    lv_obj_set_style_pad_left(ui_TextAreaRectangleHeight, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextAreaRectangleHeight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TextAreaRectangleHeight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TextAreaRectangleHeight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ContCilinder = lv_obj_create(ui_Param);
    lv_obj_remove_style_all(ui_ContCilinder);
    lv_obj_set_height(ui_ContCilinder, 44);
    lv_obj_set_width(ui_ContCilinder, lv_pct(100));
    lv_obj_set_x(ui_ContCilinder, 0);
    lv_obj_set_y(ui_ContCilinder, -10);
    lv_obj_set_align(ui_ContCilinder, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContCilinder, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContCilinder, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContCilinder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContCilinder, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContCilinder, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContCilinder, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContCilinder, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContCilinder, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContCilinder, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDiameter = lv_label_create(ui_ContCilinder);
    lv_obj_set_width(ui_lblDiameter, 115);
    lv_obj_set_height(ui_lblDiameter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDiameter, 64);
    lv_obj_set_y(ui_lblDiameter, 0);
    lv_label_set_text(ui_lblDiameter, "Diameter[mm]:");
    lv_obj_set_style_text_align(ui_lblDiameter, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHeight1 = lv_label_create(ui_ContCilinder);
    lv_obj_set_width(ui_lblHeight1, 98);
    lv_obj_set_height(ui_lblHeight1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblHeight1, 80);
    lv_obj_set_y(ui_lblHeight1, 20);
    lv_label_set_text(ui_lblHeight1, "Height[mm]:");
    lv_obj_set_style_text_align(ui_lblHeight1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label33 = lv_label_create(ui_ContCilinder);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label33, "Cilinder");

    ui_TextAreaCilinderDiameter = lv_textarea_create(ui_ContCilinder);
    lv_obj_set_width(ui_TextAreaCilinderDiameter, 110);
    lv_obj_set_height(ui_TextAreaCilinderDiameter, 20);
    lv_obj_set_x(ui_TextAreaCilinderDiameter, 189);
    lv_obj_set_y(ui_TextAreaCilinderDiameter, 0);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_TextAreaCilinderDiameter, NULL);
    else lv_textarea_set_accepted_chars(ui_TextAreaCilinderDiameter, "0123456789");
    lv_textarea_set_placeholder_text(ui_TextAreaCilinderDiameter, "1-9999");
    lv_obj_set_style_pad_left(ui_TextAreaCilinderDiameter, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextAreaCilinderDiameter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TextAreaCilinderDiameter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TextAreaCilinderDiameter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TextAreaCilinderHeight = lv_textarea_create(ui_ContCilinder);
    lv_obj_set_width(ui_TextAreaCilinderHeight, 110);
    lv_obj_set_height(ui_TextAreaCilinderHeight, 20);
    lv_obj_set_x(ui_TextAreaCilinderHeight, 189);
    lv_obj_set_y(ui_TextAreaCilinderHeight, 20);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_TextAreaCilinderHeight, NULL);
    else lv_textarea_set_accepted_chars(ui_TextAreaCilinderHeight, "0123456789");
    lv_textarea_set_placeholder_text(ui_TextAreaCilinderHeight, "1-9999");
    lv_obj_set_style_pad_left(ui_TextAreaCilinderHeight, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextAreaCilinderHeight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TextAreaCilinderHeight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TextAreaCilinderHeight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ContMinMax = lv_obj_create(ui_Param);
    lv_obj_remove_style_all(ui_ContMinMax);
    lv_obj_set_height(ui_ContMinMax, 47);
    lv_obj_set_width(ui_ContMinMax, lv_pct(100));
    lv_obj_set_x(ui_ContMinMax, 0);
    lv_obj_set_y(ui_ContMinMax, -10);
    lv_obj_set_align(ui_ContMinMax, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContMinMax, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContMinMax, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContMinMax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContMinMax, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContMinMax, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContMinMax, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContMinMax, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContMinMax, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContMinMax, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDiameter1 = lv_label_create(ui_ContMinMax);
    lv_obj_set_width(ui_lblDiameter1, 100);
    lv_obj_set_height(ui_lblDiameter1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDiameter1, 80);
    lv_obj_set_y(ui_lblDiameter1, 0);
    lv_label_set_text(ui_lblDiameter1, "Empty Tank:");
    lv_obj_set_style_text_align(ui_lblDiameter1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHeight2 = lv_label_create(ui_ContMinMax);
    lv_obj_set_width(ui_lblHeight2, 100);
    lv_obj_set_height(ui_lblHeight2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblHeight2, 80);
    lv_obj_set_y(ui_lblHeight2, 20);
    lv_label_set_text(ui_lblHeight2, "Full Tank:");
    lv_obj_set_style_text_align(ui_lblHeight2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_ContMinMax);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label34, "Distance");

    ui_TextAreaEmptyTank = lv_textarea_create(ui_ContMinMax);
    lv_obj_set_width(ui_TextAreaEmptyTank, 110);
    lv_obj_set_height(ui_TextAreaEmptyTank, 20);
    lv_obj_set_x(ui_TextAreaEmptyTank, 189);
    lv_obj_set_y(ui_TextAreaEmptyTank, 0);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_TextAreaEmptyTank, NULL);
    else lv_textarea_set_accepted_chars(ui_TextAreaEmptyTank, "0123456789");
    lv_textarea_set_placeholder_text(ui_TextAreaEmptyTank, "1-9999");
    lv_obj_set_style_pad_left(ui_TextAreaEmptyTank, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextAreaEmptyTank, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TextAreaEmptyTank, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TextAreaEmptyTank, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TextAreaFullTank = lv_textarea_create(ui_ContMinMax);
    lv_obj_set_width(ui_TextAreaFullTank, 110);
    lv_obj_set_height(ui_TextAreaFullTank, 20);
    lv_obj_set_x(ui_TextAreaFullTank, 189);
    lv_obj_set_y(ui_TextAreaFullTank, 20);
    if("0123456789" == "") lv_textarea_set_accepted_chars(ui_TextAreaFullTank, NULL);
    else lv_textarea_set_accepted_chars(ui_TextAreaFullTank, "0123456789");
    lv_textarea_set_placeholder_text(ui_TextAreaFullTank, "1-9999");
    lv_obj_set_style_pad_left(ui_TextAreaFullTank, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextAreaFullTank, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TextAreaFullTank, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TextAreaFullTank, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ContButtons = lv_obj_create(ui_Param);
    lv_obj_remove_style_all(ui_ContButtons);
    lv_obj_set_width(ui_ContButtons, lv_pct(100));
    lv_obj_set_flex_grow(ui_ContButtons, 1);
    lv_obj_set_x(ui_ContButtons, 0);
    lv_obj_set_y(ui_ContButtons, -10);
    lv_obj_set_align(ui_ContButtons, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContButtons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContButtons, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContButtons, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContButtons, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContButtons, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContButtons, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContButtons, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContButtons, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContButtons, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_ContButtons);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 25);
    lv_obj_set_align(ui_Button2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label36 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label36, "Info");

    ui_Button3 = lv_button_create(ui_ContButtons);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 25);
    lv_obj_set_align(ui_Button3, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label37 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "Save");

    ui_lblSaved = lv_label_create(ui_ContButtons);
    lv_obj_set_width(ui_lblSaved, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSaved, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblSaved, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSaved, "Saved");
    lv_obj_add_flag(ui_lblSaved, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_ParamKeyboard = lv_keyboard_create(ui_Param);
    lv_keyboard_set_mode(ui_ParamKeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_ParamKeyboard, lv_pct(100));
    lv_obj_set_flex_grow(ui_ParamKeyboard, 1);
    lv_obj_set_align(ui_ParamKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ParamKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Settings = lv_tabview_add_tab(ui_MainTabView, "Settings");
    lv_obj_set_flex_flow(ui_Settings, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Settings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Settings, LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_pad_left(ui_Settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Settings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Settings);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_height(ui_Container2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Container2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_Container2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Container2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Container2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWifiSwitch = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_lblWifiSwitch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWifiSwitch, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblWifiSwitch, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblWifiSwitch, "Network:");
    ui_object_set_themeable_style_property(ui_lblWifiSwitch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblWifiSwitch, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_btnWifi = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_btnWifi, 90);
    lv_obj_set_height(ui_btnWifi, 25);
    lv_obj_set_align(ui_btnWifi, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_btnWifi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_btnWifi);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "WiFi");
    ui_object_set_themeable_style_property(ui_Label5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_Label5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_btnMQTT = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_btnMQTT, 90);
    lv_obj_set_height(ui_btnMQTT, 25);
    lv_obj_set_x(ui_btnMQTT, -20);
    lv_obj_set_y(ui_btnMQTT, 0);
    lv_obj_set_align(ui_btnMQTT, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnMQTT, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnMQTT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label30 = lv_label_create(ui_btnMQTT);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "MQTT");
    ui_object_set_themeable_style_property(ui_Label30, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_Label30, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_ContDarkMode = lv_obj_create(ui_Settings);
    lv_obj_remove_style_all(ui_ContDarkMode);
    lv_obj_set_width(ui_ContDarkMode, lv_pct(100));
    lv_obj_set_height(ui_ContDarkMode, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ContDarkMode, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContDarkMode, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ContDarkMode, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_ContDarkMode, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_ContDarkMode, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContDarkMode, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContDarkMode, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContDarkMode, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContDarkMode, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContDarkMode, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDarkMode = lv_label_create(ui_ContDarkMode);
    lv_obj_set_width(ui_lblDarkMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDarkMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblDarkMode, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblDarkMode, "Dark Mode:");
    ui_object_set_themeable_style_property(ui_lblDarkMode, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblDarkMode, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_Switch2 = lv_switch_create(ui_ContDarkMode);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_RIGHT_MID);

    ui_object_set_themeable_style_property(ui_Switch2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_Switch2, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Border);

    ui_ContBackLigth = lv_obj_create(ui_Settings);
    lv_obj_remove_style_all(ui_ContBackLigth);
    lv_obj_set_width(ui_ContBackLigth, lv_pct(100));
    lv_obj_set_height(ui_ContBackLigth, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_x(ui_ContBackLigth, -2);
    lv_obj_set_y(ui_ContBackLigth, 13);
    lv_obj_set_align(ui_ContBackLigth, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContBackLigth, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ContBackLigth, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_ContBackLigth, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_ContBackLigth, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContBackLigth, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContBackLigth, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContBackLigth, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContBackLigth, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContBackLigth, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBackLight = lv_label_create(ui_ContBackLigth);
    lv_obj_set_width(ui_lblBackLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBackLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblBackLight, 0);
    lv_obj_set_y(ui_lblBackLight, 4);
    lv_label_set_text(ui_lblBackLight, "BackLigth (Manual/Automatic)");
    ui_object_set_themeable_style_property(ui_lblBackLight, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblBackLight, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_switchManualAutomatic = lv_switch_create(ui_ContBackLigth);
    lv_obj_set_width(ui_switchManualAutomatic, 50);
    lv_obj_set_height(ui_switchManualAutomatic, 25);
    lv_obj_set_align(ui_switchManualAutomatic, LV_ALIGN_TOP_RIGHT);

    ui_object_set_themeable_style_property(ui_switchManualAutomatic, LV_PART_INDICATOR | LV_STATE_DEFAULT,
                                           LV_STYLE_BG_COLOR, _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_switchManualAutomatic, LV_PART_INDICATOR | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Border);

    ui_Label6 = lv_label_create(ui_ContBackLigth);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 30);
    lv_label_set_text(ui_Label6, "Light Sensor (CDR):");
    ui_object_set_themeable_style_property(ui_Label6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_Label6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblLigthSensorValue = lv_label_create(ui_ContBackLigth);
    lv_obj_set_width(ui_lblLigthSensorValue, lv_pct(16));
    lv_obj_set_height(ui_lblLigthSensorValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblLigthSensorValue, 0);
    lv_obj_set_y(ui_lblLigthSensorValue, 30);
    lv_obj_set_align(ui_lblLigthSensorValue, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_lblLigthSensorValue, "600");
    ui_object_set_themeable_style_property(ui_lblLigthSensorValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblLigthSensorValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);
    lv_obj_set_style_text_align(ui_lblLigthSensorValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LigthSensorSlider = lv_slider_create(ui_ContBackLigth);
    lv_slider_set_value(ui_LigthSensorSlider, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_LigthSensorSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_LigthSensorSlider, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_height(ui_LigthSensorSlider, 15);
    lv_obj_set_width(ui_LigthSensorSlider, lv_pct(90));
    lv_obj_set_x(ui_LigthSensorSlider, 0);
    lv_obj_set_y(ui_LigthSensorSlider, 60);
    lv_obj_set_align(ui_LigthSensorSlider, LV_ALIGN_TOP_MID);


    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_LigthSensorSlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_LigthSensorSlider,
                                                                                                        lv_obj_get_style_pad_right(ui_LigthSensorSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_lblLigthSensorSliderValue = lv_label_create(ui_LigthSensorSlider);
    lv_obj_set_width(ui_lblLigthSensorSliderValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblLigthSensorSliderValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblLigthSensorSliderValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblLigthSensorSliderValue, "50%");
    ui_object_set_themeable_style_property(ui_lblLigthSensorSliderValue, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_TEXT_COLOR, _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblLigthSensorSliderValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_ContLanguage = lv_obj_create(ui_Settings);
    lv_obj_remove_style_all(ui_ContLanguage);
    lv_obj_set_width(ui_ContLanguage, lv_pct(100));
    lv_obj_set_height(ui_ContLanguage, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ContLanguage, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContLanguage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ContLanguage, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_ContLanguage, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_ContLanguage, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContLanguage, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContLanguage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContLanguage, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContLanguage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContLanguage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblLanguage = lv_label_create(ui_ContLanguage);
    lv_obj_set_width(ui_lblLanguage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblLanguage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblLanguage, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblLanguage, "Language:");
    ui_object_set_themeable_style_property(ui_lblLanguage, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblLanguage, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);
    lv_obj_set_style_text_decor(ui_lblLanguage, LV_TEXT_DECOR_STRIKETHROUGH, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownLanguage = lv_dropdown_create(ui_ContLanguage);
    lv_dropdown_set_options(ui_DropdownLanguage, "English\nMagyar");
    lv_obj_set_width(ui_DropdownLanguage, 150);
    lv_obj_set_height(ui_DropdownLanguage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownLanguage, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_DropdownLanguage, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_ContRotateScreen = lv_obj_create(ui_Settings);
    lv_obj_remove_style_all(ui_ContRotateScreen);
    lv_obj_set_width(ui_ContRotateScreen, lv_pct(100));
    lv_obj_set_height(ui_ContRotateScreen, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ContRotateScreen, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContRotateScreen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ContRotateScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_ContRotateScreen, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_ContRotateScreen, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContRotateScreen, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContRotateScreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContRotateScreen, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContRotateScreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContRotateScreen, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblrotate = lv_label_create(ui_ContRotateScreen);
    lv_obj_set_width(ui_lblrotate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblrotate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblrotate, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblrotate, "Rotate Screen:");
    ui_object_set_themeable_style_property(ui_lblrotate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblrotate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_btnRotate = lv_button_create(ui_ContRotateScreen);
    lv_obj_set_width(ui_btnRotate, 120);
    lv_obj_set_height(ui_btnRotate, 25);
    lv_obj_set_align(ui_btnRotate, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_btnRotate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnRotate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_btnRotate);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Rotate with 180°");
    ui_object_set_themeable_style_property(ui_Label7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_Label7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_ContSWReset = lv_obj_create(ui_Settings);
    lv_obj_remove_style_all(ui_ContSWReset);
    lv_obj_set_width(ui_ContSWReset, lv_pct(100));
    lv_obj_set_height(ui_ContSWReset, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ContSWReset, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContSWReset, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ContSWReset, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Border);
    ui_object_set_themeable_style_property(ui_ContSWReset, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Border);
    lv_obj_set_style_border_width(ui_ContSWReset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContSWReset, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContSWReset, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContSWReset, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContSWReset, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContSWReset, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblrotate1 = lv_label_create(ui_ContSWReset);
    lv_obj_set_width(ui_lblrotate1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblrotate1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblrotate1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblrotate1, "SW RESET:");
    ui_object_set_themeable_style_property(ui_lblrotate1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblrotate1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_btnReset = lv_button_create(ui_ContSWReset);
    lv_obj_set_width(ui_btnReset, 120);
    lv_obj_set_height(ui_btnReset, 25);
    lv_obj_set_align(ui_btnReset, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_btnReset, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnReset, lv_color_hex(0xFD0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_btnReset);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "Reset");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0x5FFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_About = lv_tabview_add_tab(ui_MainTabView, "About");
    lv_obj_set_flex_flow(ui_About, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_About, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_About, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_pad_left(ui_About, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_About, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_About, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_About, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_About, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_About, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConBuildDate = lv_obj_create(ui_About);
    lv_obj_remove_style_all(ui_ConBuildDate);
    lv_obj_set_width(ui_ConBuildDate, lv_pct(100));
    lv_obj_set_height(ui_ConBuildDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConBuildDate, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConBuildDate, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ConBuildDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConBuildDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConBuildDate, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConBuildDate, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConBuildDate, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConBuildDate, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConBuildDate, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConBuildDate, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBuildDate = lv_label_create(ui_ConBuildDate);
    lv_obj_set_width(ui_lblBuildDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBuildDate, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_lblBuildDate, "Build Date:");
    ui_object_set_themeable_style_property(ui_lblBuildDate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblBuildDate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblBuildDateValue = lv_label_create(ui_ConBuildDate);
    lv_obj_set_width(ui_lblBuildDateValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBuildDateValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblBuildDateValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lblBuildDateValue, "Oct 99 2099 12:22:36");
    ui_object_set_themeable_style_property(ui_lblBuildDateValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblBuildDateValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_ConBuildVersion = lv_obj_create(ui_About);
    lv_obj_remove_style_all(ui_ConBuildVersion);
    lv_obj_set_width(ui_ConBuildVersion, lv_pct(100));
    lv_obj_set_height(ui_ConBuildVersion, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ConBuildVersion, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConBuildVersion, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ConBuildVersion, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConBuildVersion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConBuildVersion, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConBuildVersion, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConBuildVersion, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConBuildVersion, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConBuildVersion, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConBuildVersion, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblBuildVersion = lv_label_create(ui_ConBuildVersion);
    lv_obj_set_width(ui_lblBuildVersion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBuildVersion, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_lblBuildVersion, "Build Version:");
    ui_object_set_themeable_style_property(ui_lblBuildVersion, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblBuildVersion, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblBuildVersionValue = lv_label_create(ui_ConBuildVersion);
    lv_obj_set_width(ui_lblBuildVersionValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblBuildVersionValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblBuildVersionValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lblBuildVersionValue, "99.99.999");
    ui_object_set_themeable_style_property(ui_lblBuildVersionValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblBuildVersionValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_btnFWUpdate = lv_button_create(ui_ConBuildVersion);
    lv_obj_set_width(ui_btnFWUpdate, 100);
    lv_obj_set_height(ui_btnFWUpdate, 20);
    lv_obj_set_x(ui_btnFWUpdate, 15);
    lv_obj_set_y(ui_btnFWUpdate, 0);
    lv_obj_set_align(ui_btnFWUpdate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnFWUpdate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnFWUpdate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label38 = lv_label_create(ui_btnFWUpdate);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "Check FW");

    ui_ConRunTime = lv_obj_create(ui_About);
    lv_obj_remove_style_all(ui_ConRunTime);
    lv_obj_set_width(ui_ConRunTime, lv_pct(100));
    lv_obj_set_height(ui_ConRunTime, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ConRunTime, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConRunTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ConRunTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConRunTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConRunTime, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConRunTime, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConRunTime, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConRunTime, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConRunTime, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConRunTime, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRunTime = lv_label_create(ui_ConRunTime);
    lv_obj_set_width(ui_lblRunTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRunTime, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_lblRunTime, "RunTime (y-d h:m:s):");
    ui_object_set_themeable_style_property(ui_lblRunTime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblRunTime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblRunTimeValue = lv_label_create(ui_ConRunTime);
    lv_obj_set_width(ui_lblRunTimeValue, lv_pct(46));
    lv_obj_set_height(ui_lblRunTimeValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblRunTimeValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lblRunTimeValue, "99-999 99:99:99.9");
    ui_object_set_themeable_style_property(ui_lblRunTimeValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblRunTimeValue, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);
    lv_obj_set_style_text_align(ui_lblRunTimeValue, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRunTimeValue, &ui_font_DejaVuSansMono14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConGitHub = lv_obj_create(ui_About);
    lv_obj_remove_style_all(ui_ConGitHub);
    lv_obj_set_width(ui_ConGitHub, lv_pct(100));
    lv_obj_set_height(ui_ConGitHub, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ConGitHub, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConGitHub, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ConGitHub, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConGitHub, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConGitHub, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConGitHub, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConGitHub, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConGitHub, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConGitHub, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConGitHub, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblGit = lv_label_create(ui_ConGitHub);
    lv_obj_set_width(ui_lblGit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblGit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblGit, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblGit, "GitHub:");
    ui_object_set_themeable_style_property(ui_lblGit, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblGit, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblGitHub = lv_label_create(ui_ConGitHub);
    lv_obj_set_width(ui_lblGitHub, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblGitHub, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblGitHub, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lblGitHub, "https://github.com/\nKislac/water-tank-monitor");
    ui_object_set_themeable_style_property(ui_lblGitHub, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblGitHub, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);
    lv_obj_set_style_text_align(ui_lblGitHub, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConAuth = lv_obj_create(ui_About);
    lv_obj_remove_style_all(ui_ConAuth);
    lv_obj_set_width(ui_ConAuth, lv_pct(100));
    lv_obj_set_height(ui_ConAuth, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ConAuth, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConAuth, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ConAuth, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConAuth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConAuth, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConAuth, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConAuth, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConAuth, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConAuth, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConAuth, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblGit1 = lv_label_create(ui_ConAuth);
    lv_obj_set_width(ui_lblGit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblGit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblGit1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_lblGit1, "Author:");
    ui_object_set_themeable_style_property(ui_lblGit1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblGit1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_lblGitHub1 = lv_label_create(ui_ConAuth);
    lv_obj_set_width(ui_lblGitHub1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblGitHub1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblGitHub1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_lblGitHub1, "Kis László Dániel\nkislac66@gmail.com");
    ui_object_set_themeable_style_property(ui_lblGitHub1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblGitHub1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);
    lv_obj_set_style_text_align(ui_lblGitHub1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblGitHub1, &ui_font_MontserratRegular14ExtASCIMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConPayPall = lv_obj_create(ui_About);
    lv_obj_remove_style_all(ui_ConPayPall);
    lv_obj_set_width(ui_ConPayPall, lv_pct(100));
    lv_obj_set_height(ui_ConPayPall, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_ConPayPall, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConPayPall, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ConPayPall, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConPayPall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConPayPall, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ConPayPall, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConPayPall, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConPayPall, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConPayPall, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConPayPall, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblGit2 = lv_label_create(ui_ConPayPall);
    lv_obj_set_width(ui_lblGit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblGit2, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_lblGit2, "Buy me a coffe");
    ui_object_set_themeable_style_property(ui_lblGit2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblGit2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);

    ui_Button8 = lv_button_create(ui_ConPayPall);
    lv_obj_set_width(ui_Button8, 100);
    lv_obj_set_height(ui_Button8, 25);
    lv_obj_set_align(ui_Button8, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblPaypall = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_lblPaypall, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPaypall, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblPaypall, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPaypall, "PayPall");
    ui_object_set_themeable_style_property(ui_lblPaypall, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_FontColor);
    ui_object_set_themeable_style_property(ui_lblPaypall, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_FontColor);
    lv_obj_set_style_text_align(ui_lblPaypall, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblPaypall, &ui_font_MontserratRegular14ExtASCIMedium, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_ConPayPall);
    lv_image_set_src(ui_Image1, &ui_img_qrcode_2_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, 25);
    lv_obj_set_align(ui_Image1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DropdownParamTankType, ui_event_DropdownParamTankType, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaRectangleWide, ui_event_TextAreaRectangleWide, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaRectangleDepth, ui_event_TextAreaRectangleDepth, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaRectangleHeight, ui_event_TextAreaRectangleHeight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaCilinderDiameter, ui_event_TextAreaCilinderDiameter, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaCilinderHeight, ui_event_TextAreaCilinderHeight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaEmptyTank, ui_event_TextAreaEmptyTank, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaFullTank, ui_event_TextAreaFullTank, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_ParamKeyboard, ui_TextAreaRectangleWide);
    lv_obj_add_event_cb(ui_ParamKeyboard, ui_event_ParamKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnWifi, ui_event_btnWifi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnMQTT, ui_event_btnMQTT, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switchManualAutomatic, ui_event_switchManualAutomatic, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LigthSensorSlider, ui_event_LigthSensorSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRotate, ui_event_btnRotate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnReset, ui_event_btnReset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnFWUpdate, ui_event_btnFWUpdate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);

}
